# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Edin's Blog
tagline:          'A Jekyll theme'
description:      'Malo o ovome, malo o onome. Najviše o svemu.'
url:              http://blog.edinc.info
baseurl:          /

author:
  name:           'Edin Cenanovic'
  url:            https://twitter.com/ecenanovic

paginate:         5

# Custom vars
plugins:             [jekyll-paginate]

github:
  repo:           https://github.com/poole/hyde
